# Generated by Django 4.2.7 on 2025-11-07 10:02

import uuid
from django.db import migrations, models


def generate_uuids_for_existing_users(apps, schema_editor):
    BaseUserDetails = apps.get_model('core', 'BaseUserDetails')
    for user in BaseUserDetails.objects.all():
        user.uuid = uuid.uuid4()
        user.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_baseuserdetails_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuserdetails',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.RunPython(
            generate_uuids_for_existing_users,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
