# Generated by Django 4.2.7 on 2025-12-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=8)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True)),
                ('signup_data', models.JSONField()),
            ],
            options={
                'db_table': 'pending_signups',
                'indexes': [models.Index(fields=['email'], name='pending_sig_email_9d6145_idx')],
            },
        ),
    ]
