# Generated by Django 4.2.7 on 2025-12-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pendingsignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
