# Generated by Django 4.2.7 on 2025-11-07 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_uuid_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuserdetails',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='baseuserdetails',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baseuserdetails',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
