# Generated by Django 4.2.7 on 2025-12-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
