# Generated by Django 4.2.7 on 2025-12-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_subscription'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
