# Generated by Django 4.2.7 on 2025-11-07 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('property_type', models.CharField(blank=True, help_text='Comma-separated list of property types (HOUSE, CONDO, TOWNHOUSE, APARTMENT, LAND, COMMERCIAL)', max_length=500, null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seller_description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Profile',
                'verbose_name_plural': 'Seller Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealtorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('professional_summary', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Realtor Profile',
                'verbose_name_plural': 'Realtor Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_areas', models.TextField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('business_license_number', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Profile',
                'verbose_name_plural': 'Partner Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('budget_range', models.CharField(blank=True, choices=[('0-200000', '$0 - $200,000'), ('200000-400000', '$200,000 - $400,000'), ('400000-600000', '$400,000 - $600,000'), ('600000-800000', '$600,000 - $800,000'), ('800000-1000000', '$800,000 - $1,000,000'), ('1000000+', '$1,000,000+')], max_length=50, null=True)),
                ('preferred_locations', models.TextField(blank=True, help_text='Comma-separated list of preferred locations', null=True)),
                ('property_type', models.CharField(blank=True, help_text='Comma-separated list of property types (HOUSE, CONDO, TOWNHOUSE, APARTMENT, LAND, COMMERCIAL)', max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer Profile',
                'verbose_name_plural': 'Buyer Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
