# Generated by Django 4.2.7 on 2025-11-09 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuyerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_location",
                    models.CharField(
                        blank=True,
                        help_text="City, State for property search",
                        max_length=255,
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        blank=True,
                        help_text="Budget range for property purchase",
                        max_length=100,
                    ),
                ),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[("BASIC", "Basic Plan"), ("PRO", "Pro Plan")],
                        default="BASIC",
                        max_length=50,
                    ),
                ),
                (
                    "subscription_start_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("subscription_end_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "buyer_profiles",
            },
        ),
        migrations.CreateModel(
            name="PartnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Business or company name", max_length=255
                    ),
                ),
                (
                    "partnership_type",
                    models.CharField(
                        choices=[
                            ("MORTGAGE", "Mortgage Lender"),
                            ("INSURANCE", "Insurance Provider"),
                            ("INSPECTION", "Home Inspection"),
                            ("LEGAL", "Legal Services"),
                            ("CONTRACTOR", "Contractor"),
                            ("OTHER", "Other Services"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "service_areas",
                    models.TextField(
                        help_text="Cities or regions served (comma-separated)"
                    ),
                ),
                ("subscription_active", models.BooleanField(default=False)),
                (
                    "subscription_start_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "partner_profiles",
            },
        ),
        migrations.CreateModel(
            name="RealtorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        help_text="Real estate license number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "company_brokerage",
                    models.CharField(
                        help_text="Company or brokerage name", max_length=255
                    ),
                ),
                (
                    "years_of_experience",
                    models.CharField(
                        choices=[
                            ("ENTRY", "0-2 years"),
                            ("INTERMEDIATE", "3-5 years"),
                            ("EXPERIENCED", "6-10 years"),
                            ("EXPERT", "10+ years"),
                        ],
                        default="ENTRY",
                        max_length=20,
                    ),
                ),
                ("subscription_active", models.BooleanField(default=False)),
                (
                    "subscription_start_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "realtor_profiles",
            },
        ),
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RESIDENTIAL", "Residential"),
                            ("COMMERCIAL", "Commercial"),
                            ("LAND", "Land"),
                            ("MULTI_FAMILY", "Multi-Family"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "property_location",
                    models.CharField(
                        blank=True,
                        help_text="City, State where property is located",
                        max_length=255,
                    ),
                ),
                ("has_active_listing", models.BooleanField(default=False)),
                ("listing_created_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "seller_profiles",
            },
        ),
    ]
