# Generated by Django 4.2.7 on 2025-11-09 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'SELLER'}, on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realtorprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'REALTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='realtor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'PARTNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'BUYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='realtorprofile',
            index=models.Index(fields=['license_number'], name='realtor_pro_license_ec585d_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerprofile',
            index=models.Index(fields=['partnership_type'], name='partner_pro_partner_3ad19d_idx'),
        ),
    ]
