# Generated by Django 4.2.7 on 2025-11-10 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_partnerprofile_business_license_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerprofile",
            name="assigned_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned realtor/agent for this buyer",
                limit_choices_to={"role": "REALTOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_buyers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
