# Generated by Django 4.2.7 on 2025-11-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_buyerprofile_assigned_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtorprofile",
            name="description",
            field=models.TextField(
                blank=True, help_text="Professional bio or description"
            ),
        ),
    ]
