# Generated by Django 4.2.7 on 2025-11-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_realtorprofile_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerprofile",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SINGLE_FAMILY", "Single family"),
                    ("CONDO", "Condo"),
                    ("TOWNHOME", "Townhome"),
                    ("APARTMENT_UNIT", "Apartment unit"),
                ],
                max_length=50,
            ),
        ),
    ]
