# Generated by Django 4.2.7 on 2025-11-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_sellerprofile_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="address_number",
            field=models.CharField(
                blank=True, help_text="Street number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="city",
            field=models.CharField(blank=True, help_text="City", max_length=100),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="county",
            field=models.CharField(blank=True, help_text="County", max_length=100),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="leaseback_required",
            field=models.BooleanField(
                default=False, help_text="Whether seller requires leaseback arrangement"
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="property_description",
            field=models.TextField(
                blank=True, help_text="Detailed property description"
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="reason_for_selling",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UPSIZING", "Upsizing"),
                    ("DOWNSIZING", "Downsizing"),
                    ("RELOCATION", "Relocation"),
                    ("FINANCIAL", "Financial Reasons"),
                    ("DIVORCE", "Divorce/Separation"),
                    ("INHERITED", "Inherited Property"),
                    ("INVESTMENT", "Investment Property Sale"),
                    ("OTHER", "Other"),
                ],
                help_text="Reason for selling the property",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="selling_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FSBO", "For Sale By Owner (FSBO)"),
                    ("WITH_AGENT", "With Real Estate Agent"),
                    ("CASH_BUYER", "Cash Buyer"),
                    ("AUCTION", "Auction"),
                ],
                help_text="Type of sale",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="state",
            field=models.CharField(blank=True, help_text="State", max_length=50),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="street_address",
            field=models.CharField(
                blank=True, help_text="Street name and type", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="zip_code",
            field=models.CharField(
                blank=True, help_text="ZIP/Postal code", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="property_location",
            field=models.CharField(
                blank=True,
                help_text="City, State where property is located (legacy field)",
                max_length=255,
            ),
        ),
    ]
