# Generated by Django 4.2.7 on 2025-12-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sellerprofile_address_number_sellerprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Number of bathrooms', max_digits=4),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bedrooms',
            field=models.IntegerField(default=0, help_text='Number of bedrooms'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='garage_spaces',
            field=models.IntegerField(default=0, help_text='Garage spaces'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='property_features',
            field=models.JSONField(blank=True, default=dict, help_text='Structured property features'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='sqft',
            field=models.IntegerField(default=0, help_text='Square footage'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.sellerprofile')),
            ],
            options={
                'db_table': 'property_images',
            },
        ),
    ]
