# Generated by Django 4.2.7 on 2025-12-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sellerprofile_bathrooms_sellerprofile_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='is_active_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
