# Generated by Django 4.2.7 on 2025-12-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_buyerprofile_is_active_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, help_text='Properties favorited by this buyer', related_name='favorited_by', to='api.sellerprofile'),
        ),
    ]
