# Generated by Django 4.2.7 on 2025-12-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_buyerprofile_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='subscription_active',
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='is_active_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
