# Generated by Django 4.2.7 on 2025-12-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_partnerprofile_subscription_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtorprofile',
            old_name='subscription_active',
            new_name='is_active_subscription',
        ),
    ]
