# Generated by Django 4.2.7 on 2025-12-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_subscription_active_realtorprofile_is_active_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='subscription_start_date',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='subscription_start_date',
        ),
        migrations.RemoveField(
            model_name='realtorprofile',
            name='subscription_start_date',
        ),
    ]
