# Generated by Django 4.2.7 on 2025-12-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_buyerprofile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='is_active_subscription',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='is_active_subscription',
        ),
        migrations.RemoveField(
            model_name='realtorprofile',
            name='is_active_subscription',
        ),
    ]
