# Generated by Django 4.2.7 on 2025-12-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_buyerprofile_is_active_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='address_number',
            field=models.CharField(blank=True, help_text='Street number', max_length=50),
        ),
    ]
