# Generated by Django 4.2.7 on 2025-12-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_sellerprofile_address_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellerprofile",
            name="reason_for_selling",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="selling_type",
        ),
    ]
