# Generated by Django 4.2.7 on 2025-12-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_sellerprofile_reason_for_selling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='access_pass_active',
            field=models.BooleanField(default=False, help_text='Is Access Pass currently active'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='access_pass_expiry_date',
            field=models.DateTimeField(blank=True, help_text='When current Access Pass expires', null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='is_member',
            field=models.BooleanField(default=False, help_text='Is active Buyer Member'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='membership_end_date',
            field=models.DateTimeField(blank=True, help_text='Next billing date or expiration', null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='membership_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='unlocked_sellers',
            field=models.ManyToManyField(blank=True, help_text='Sellers whose contact info has been unlocked', related_name='unlocked_by_buyers', to='api.sellerprofile'),
        ),
    ]
