# Generated by Django 4.2.7 on 2025-12-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_buyerprofile_access_pass_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='access_pass_active',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='access_pass_expiry_date',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='is_member',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='unlocked_sellers',
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='access_pass_expiry',
            field=models.DateTimeField(blank=True, help_text='Expiration date of the current Access Pass', null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='access_pass_extensions_used',
            field=models.IntegerField(default=0, help_text='Number of extensions used (max 2)'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='is_membership_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='membership_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
