# Generated by Django 4.2.7 on 2025-12-30 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_remove_buyerprofile_access_pass_active_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='partnerprofile',
            name='partner_pro_partner_3ad19d_idx',
        ),
        migrations.RemoveIndex(
            model_name='realtorprofile',
            name='realtor_pro_license_ec585d_idx',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='membership_start_date',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='listing_created_at',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='property_location',
        ),
        migrations.AddField(
            model_name='realtorprofile',
            name='is_active_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realtorprofile',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_buyers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('0-200000', '$0 - $200,000'), ('200000-400000', '$200,000 - $400,000'), ('400000-600000', '$400,000 - $600,000'), ('600000-800000', '$600,000 - $800,000'), ('800000-1000000', '$800,000 - $1,000,000'), ('1000000+', '$1,000,000+')], max_length=100),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='api.sellerprofile'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='business_license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='partnership_type',
            field=models.CharField(choices=[('REAL_ESTATE_AGENT', 'Real Estate Agency'), ('MORTGAGE', 'Mortgage Lender'), ('HOME_INSPECTION', 'Home Inspector'), ('CONTRACTOR', 'Contractor'), ('MOVING_COMPANY', 'Moving Company'), ('PROPERTY_APPRAISER', 'Property Appraiser'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='service_areas',
            field=models.TextField(help_text='Cities or regions served'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='realtorprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='realtorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='address_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='garage_spaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='leaseback_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='property_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='property_features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='property_type',
            field=models.CharField(blank=True, choices=[('SINGLE_FAMILY', 'Single Family'), ('CONDO', 'Condo'), ('TOWNHOME', 'Townhome'), ('APARTMENT_UNIT', 'Apartment Unit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='sqft',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
