# Generated by Django 4.2.7 on 2025-12-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_partnerprofile_partner_pro_partner_3ad19d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('realtor', 'Realtor'), ('partner', 'Partner')], max_length=20, unique=True)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('access_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('listing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('buyer_upfront_price', models.DecimalField(decimal_places=2, default=0, help_text='For Buyer Membership (upfront)', max_digits=10)),
                ('buyer_monthly_price', models.DecimalField(decimal_places=2, default=0, help_text='For Buyer Membership (monthly)', max_digits=10)),
                ('buyer_access_pass_price', models.DecimalField(decimal_places=2, default=0, help_text='For Buyer Access Pass', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pricing_plans',
            },
        ),
    ]
