# Generated by Django 4.2.7 on 2025-12-30 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_pricingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='api.sellerprofile')),
            ],
            options={
                'db_table': 'property_views',
                'indexes': [models.Index(fields=['seller_profile', 'ip_address'], name='property_vi_seller__423edd_idx')],
                'unique_together': {('seller_profile', 'ip_address')},
            },
        ),
    ]
