# Generated by Django 4.2.7 on 2025-12-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_propertyview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('days_duration', models.IntegerField(default=30)),
                ('extension_days', models.IntegerField(default=15, help_text='Number of days given per extension')),
                ('extension_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_extensions', models.IntegerField(default=2)),
                ('properties_limit', models.IntegerField(default=10, help_text='Number of properties this pass unlocks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'access_pass_types',
            },
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='buyer_min_months',
            field=models.IntegerField(default=3, help_text='Minimum months for initial subscription'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='buyer_access_pass_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy: Basic Access Pass Price', max_digits=10),
        ),
    ]
