# Generated by Django 4.2.7 on 2026-01-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_accesspasstype_pricingplan_buyer_min_months_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerprofile",
            name="partnership_type",
            field=models.CharField(
                choices=[
                    ("REAL_ESTATE_AGENT", "Real Estate Agency"),
                    ("MORTGAGE", "Mortgage Lender"),
                    ("HOME_INSPECTION", "Home Inspector"),
                    ("CONTRACTOR", "Contractor"),
                    ("MOVING_COMPANY", "Moving Company"),
                    ("PROPERTY_APPRAISER", "Property Appraiser"),
                    ("TITLE_COMPANY", "Title Company"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
