# Generated by Django 4.2.7 on 2026-01-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_partnerprofile_partnership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='current_access_pass_extension_days',
            field=models.IntegerField(default=15, help_text='Snapshot of extension days at time of purchase'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='current_access_pass_extension_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Snapshot of extension price at time of purchase', max_digits=10),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='current_access_pass_limit',
            field=models.IntegerField(default=10, help_text='Snapshot of property limit at time of purchase'),
        ),
    ]
