# Generated by Django 4.2.7 on 2026-01-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_buyerprofile_current_access_pass_extension_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerRealtorConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtor_connections', to='api.buyerprofile')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_requests', to='api.realtorprofile')),
            ],
            options={
                'db_table': 'buyer_realtor_connections',
                'unique_together': {('buyer', 'realtor')},
            },
        ),
    ]
