# Generated by Django 4.2.7 on 2026-01-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_buyerrealtorconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtorprofile',
            name='location',
            field=models.CharField(blank=True, help_text='City, State', max_length=255),
        ),
    ]
