# Generated by Django 4.2.7 on 2026-01-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_realtorprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='realtorprofile',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
