# Generated by Django 4.2.7 on 2026-01-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_realtorprofile_rating_realtorprofile_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='assigned_realtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sellers', to='api.realtorprofile'),
        ),
    ]
