# Generated by Django 4.2.7 on 2026-01-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_sellerprofile_assigned_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='client_status',
            field=models.JSONField(blank=True, default=dict, help_text="Tracks realtor's progress with this seller/client"),
        ),
    ]
